@echo off
setlocal enabledelayedexpansion
title XaClient Launcher

set "REPO=Xani4kaGitHub/XaClient"
set "MODS=%APPDATA%\.minecraft\mods"
if not exist "%MODS%" mkdir "%MODS%"

:: Enable ANSI Escape Codes
for /F %%a in ('echo prompt $E ^| cmd') do set "ESC=%%a"

cls
echo.
echo %ESC%[95m____  ___      _________ .__  .__               __
echo \   \/  /____  \_   ___ \^|  ^| ^|__^| ____   _____/  ^|_
echo  \     /\__  \ /    \  \/^|  ^| ^|  ^|/ __ \ /    \   __\
echo  /     \ / __ \\     \___^|  ^|_^|  \  ___/^|   ^|  \  ^|
echo /___/\  (____  /\______  /____/__^|\___  ^>___^|  /__^|
echo       \_/    \/        \/             \/     \/     %ESC%[0m
echo.
echo  %ESC%[95m::%ESC%[97m Checking for updates...%ESC%[0m
echo.

powershell -NoProfile -ExecutionPolicy Bypass -EncodedCommand JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKACQAcgBlAHAAbwAgAD0AIAAkAGUAbgB2ADoAUgBFAFAATwAKACQAbQBvAGQAcwAgAD0AIAAkAGUAbgB2ADoATQBPAEQAUwAKACQAZQAgAD0AIABbAGMAaABhAHIAXQAyADcACgBmAHUAbgBjAHQAaQBvAG4AIABvAGsAKAAkAG0AKQAgACAAewAgAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiACQAZQBbADkANQBtACAAIAA+AD4AIAAkAGUAWwA5ADcAbQAkAG0AJABlAFsAMABtACIAIAB9AAoAZgB1AG4AYwB0AGkAbwBuACAAYgBhAGQAKAAkAG0AKQAgAHsAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAkAGUAWwA5ADEAbQAgACAAPgA+ACAAJABtACQAZQBbADAAbQAiACAAfQAKAAoAdAByAHkAIAB7AAoAIAAgACAAIAAkAGgAIAA9ACAAQAB7ACAAJwBVAHMAZQByAC0AQQBnAGUAbgB0ACcAIAA9ACAAJwBYAGEAQwBsAGkAZQBuAHQAJwAgAH0ACgAgACAAIAAgACQAcgAgAD0AIABJAG4AdgBvAGsAZQAtAFIAZQBzAHQATQBlAHQAaABvAGQAIAAtAEgAZQBhAGQAZQByAHMAIAAkAGgAIAAiAGgAdAB0AHAAcwA6AC8ALwBhAHAAaQAuAGcAaQB0AGgAdQBiAC4AYwBvAG0ALwByAGUAcABvAHMALwAkAHIAZQBwAG8ALwByAGUAbABlAGEAcwBlAHMALwBsAGEAdABlAHMAdAAiAAoAIAAgACAAIAAkAHQAYQBnACAAPQAgACQAcgAuAHQAYQBnAF8AbgBhAG0AZQAKACAAIAAgACAAJABhAHMAcwBlAHQAIAA9ACAAJAByAC4AYQBzAHMAZQB0AHMAIAB8ACAAVwBoAGUAcgBlAC0ATwBiAGoAZQBjAHQAIAB7ACAAJABfAC4AbgBhAG0AZQAgAC0AbABpAGsAZQAgACcAKgAuAGoAYQByACcAIAAtAGEAbgBkACAAJABfAC4AbgBhAG0AZQAgAC0AbgBvAHQAbABpAGsAZQAgACcAKgBzAG8AdQByAGMAZQBzACoAJwAgAH0AIAB8ACAAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAAMQAKACAAIAAgACAAaQBmACAAKAAtAG4AbwB0ACAAJABhAHMAcwBlAHQAKQAgAHsAIABiAGEAZAAgACcATgBvACAALgBqAGEAcgAgAGYAbwB1AG4AZAAgAGkAbgAgAHQAaABlACAAbABhAHQAZQBzAHQAIAByAGUAbABlAGEAcwBlACcAOwAgAGUAeABpAHQAIAAxACAAfQAKAAoAIAAgACAAIAAkAHYAZQByAEYAaQBsAGUAIAA9ACAASgBvAGkAbgAtAFAAYQB0AGgAIAAkAG0AbwBkAHMAIAAnAC4AeABhAGMAbABpAGUAbgB0AF8AdgBlAHIAcwBpAG8AbgAnAAoAIAAgACAAIAAkAGwAbwBjAGEAbAAgAD0AIABpAGYAIAAoAFQAZQBzAHQALQBQAGEAdABoACAAJAB2AGUAcgBGAGkAbABlACkAIAB7ACAAKABHAGUAdAAtAEMAbwBuAHQAZQBuAHQAIAAkAHYAZQByAEYAaQBsAGUAIAAtAFIAYQB3ACkALgBUAHIAaQBtACgAKQAgAH0AIABlAGwAcwBlACAAewAgACcAJwAgAH0ACgAKACAAIAAgACAAaQBmACAAKAAkAGwAbwBjAGEAbAAgAC0AZQBxACAAJAB0AGEAZwApACAAewAKACAAIAAgACAAIAAgACAAIABvAGsAIAAiAEwAYQB0AGUAcwB0ACAAdgBlAHIAcwBpAG8AbgAgAGkAbgBzAHQAYQBsAGwAZQBkACAAKAAkAHQAYQBnACkAIgAKACAAIAAgACAAIAAgACAAIABlAHgAaQB0ACAAMAAKACAAIAAgACAAfQAKAAoAIAAgACAAIABvAGsAIAAiAEQAbwB3AG4AbABvAGEAZABpAG4AZwAgACQAdABhAGcAIAAuAC4ALgAiAAoAIAAgACAAIABHAGUAdAAtAEMAaABpAGwAZABJAHQAZQBtACAAJABtAG8AZABzACAALQBGAGkAbAB0AGUAcgAgACcAeABhAGMAbABpAGUAbgB0ACoALgBqAGEAcgAnACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlACAAfAAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgAC0ARgBvAHIAYwBlAAoAIAAgACAAIABJAG4AdgBvAGsAZQAtAFcAZQBiAFIAZQBxAHUAZQBzAHQAIAAtAEgAZQBhAGQAZQByAHMAIAAkAGgAIAAkAGEAcwBzAGUAdAAuAGIAcgBvAHcAcwBlAHIAXwBkAG8AdwBuAGwAbwBhAGQAXwB1AHIAbAAgAC0ATwB1AHQARgBpAGwAZQAgACgASgBvAGkAbgAtAFAAYQB0AGgAIAAkAG0AbwBkAHMAIAAkAGEAcwBzAGUAdAAuAG4AYQBtAGUAKQAKACAAIAAgACAAUwBlAHQALQBDAG8AbgB0AGUAbgB0ACAAJAB2AGUAcgBGAGkAbABlACAAJAB0AGEAZwAKACAAIAAgACAAbwBrACAAIgBVAHAAZABhAHQAZQBkACAAdABvACAAJAB0AGEAZwAiAAoAfQAKAGMAYQB0AGMAaAAgAHsACgAgACAAIAAgAGIAYQBkACAAKAAiAEUAcgByAG8AcgA6ACAAIgAgACsAIAAkAF8ALgBFAHgAYwBlAHAAdABpAG8AbgAuAE0AZQBzAHMAYQBnAGUAKQAKAH0ACgA=

echo.
echo  %ESC%[95m[*]%ESC%[97m Launching Minecraft...%ESC%[0m
echo.
start "" "minecraft://"
echo  %ESC%[95m » %ESC%[97mIn the launcher pick the %ESC%[95mFabric 1.21.4%ESC%[97m profile and press Play.%ESC%[0m
echo.
pause
